
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "nc", "-z", "zookeeper", "2181"]
      interval: 30s
      retries: 5
    depends_on:
      - zookeeper
    command: /bin/sh -c "sleep 5; /etc/confluent/docker/run"

  distributor:
    build:
      context: ./distributor
    command: /bin/sh -c "sleep 10 && python3 distributor.py"
    container_name: distributor
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

  atlanta:
    build:
      context: ./hospitals
    command: /bin/sh -c "sleep 10 && python3 atlanta.py"
    container_name: atlanta
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

  boston:
    build:
      context: ./hospitals
    command: /bin/sh -c "sleep 10 && python3 boston.py"
    container_name: boston
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

  chicago:
    build:
      context: ./hospitals
    command: /bin/sh -c "sleep 10 && python3 chicago.py"
    container_name: chicago
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

  senior:
    container_name: senior
    build: ./topics/senior
    ports:
      - "7079:7077"
      - "8082:8080"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    volumes:
      - ./spark-modules:/opt/spark-modules # It's a temporary volume for testing.

  dallas:
    build:
      context: ./hospitals
    command: /bin/sh -c "sleep 10 && python3 dallas.py"
    container_name: dallas
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
  
  detroit:
    build:
      context: ./hospitals
    command: /bin/sh -c "sleep 10 && python3 detroit.py"
    container_name: detroit
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
  
  houston:
    build:
      context: ./hospitals
    command: /bin/sh -c "sleep 10 && python3 houston.py"
    container_name: houston
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
  
  jersey:
    build:
      context: ./hospitals
    command: /bin/sh -c "sleep 10 && python3 jersey.py"
    container_name: jersey
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
  
  miami:
    build:
      context: ./hospitals
    command: /bin/sh -c "sleep 10 && python3 miami.py"
    container_name: miami
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
  
  newyork:
    build:
      context: ./hospitals
    command: /bin/sh -c "sleep 10 && python3 newyork.py"
    container_name: newyork
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
  
  phoenix:
    build:
      context: ./hospitals
    command: /bin/sh -c "sleep 10 && python3 phoenix.py"
    container_name: phoenix
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
  
  sanfrancisco:
    build:
      context: ./hospitals
    command: /bin/sh -c "sleep 10 && python3 sanfrancisco.py"
    container_name: sanfrancisco
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
  
  seattle:
    build:
      context: ./hospitals
    command: /bin/sh -c "sleep 10 && python3 seattle.py"
    container_name: seattle
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
  
  washington:
    build:
      context: ./hospitals
    command: /bin/sh -c "sleep 10 && python3 washington.py"
    container_name: washington
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

  consumer:
    build:
      context: ./consumer
    container_name: consumer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
