services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_PORT: 9092
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server=kafka:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - zookeeper

  atlanta:
    build:
      context: ./hospitals
    command: python3 atlanta.py
    container_name: atlanta
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

  boston:
    build:
      context: ./hospitals
    command: python3 boston.py
    container_name: boston
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

  chicago:
    build:
      context: ./hospitals
    command: python3 chicago.py
    container_name: chicago
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

  dallas:
    build:
      context: ./hospitals
    command: python3 dallas.py
    container_name: dallas
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
  
  detroit:
    build:
      context: ./hospitals
    command: python3 detroit.py
    container_name: detroit
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
  
  houston:
    build:
      context: ./hospitals
    command: python3 houston.py
    container_name: houston
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
  
  jersey:
    build:
      context: ./hospitals
    command: python3 jersey.py
    container_name: jersey
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
  
  miami:
    build:
      context: ./hospitals
    command: python3 miami.py
    container_name: miami
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
  
  newyork:
    build:
      context: ./hospitals
    command: python3 newyork.py
    container_name: newyork
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
  
  phoenix:
    build:
      context: ./hospitals
    command: python3 phoenix.py
    container_name: phoenix
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
  
  sanfrancisco:
    build:
      context: ./hospitals
    command: python3 sanfrancisco.py
    container_name: sanfrancisco
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
  
  seattle:
    build:
      context: ./hospitals
    command: python3 seattle.py
    container_name: seattle
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
  
  washington:
    build:
      context: ./hospitals
    command: python3 washington.py
    container_name: washington
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

  consumer:
    build:
      context: ./consumer
    container_name: consumer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
